# A string used to distinguish different Supabase projects on the same machine.
# Not required if you have a single project.
project_id = "navigapp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_signup = true
enable_anonymous_sign_ins = false

[edge_functions]
enabled = true

[functions.navigapp-api]
verify_jwt = false

[functions.test-api]
verify_jwt = false